### ISSUE TITLE
Very Fast Block Breaking

### ISSUE THREAD

**Issue by ugury3806** [Wartori54/TRC-No-Lag#2]
Hi. Even if I set tickrate to 20 it's still breaks blocks very fast. On survival mod tools working a bit faster and on creative mod it breaks everything. Create a new creative world and hold on left click you'll see it.

**Comment by Wartori54** [comment]
Yeah i already knew that issue. It's due to the block breaking being handled every frame instead of every tick. Just try to click fast.

This (probably) wont be fixed soon.
