### ISSUE TITLE
Java 16 minecraft

### ISSUE THREAD

**Issue by MrXeMan** [Wartori54/TRC-No-Lag#3]
With mod server automatically closes with errors.
The server runs with Java 16, and probably the problem is with a mod and Java 16.
![image](https://user-images.githubusercontent.com/95623244/144840412-8f533982-b531-4d96-b486-d9e09b107b2a.png)

**Comment by Wartori54** [comment]
Do you have other mods? If yes, does minecraft also crash without this mod?

Can you post the entire crash log?

**Comment by MrXeMan** [comment]
Yes, I have fabric API so the mod can work. No, without the mod, the server doesn't crush.
Here is the entire crash log:
https://mclo.gs/7lfyzEn

**Comment by Wartori54** [comment]
Should be fixed in 0.3. If not reopen issue.
